# Generated by Django 3.1.1 on 2020-09-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('geo', models.CharField(blank=True, max_length=32, null=True, verbose_name='GEO')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('group', models.CharField(blank=True, max_length=64, null=True, verbose_name='Group')),
                ('network', models.CharField(blank=True, max_length=64, null=True, verbose_name='Network')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=128, null=True, verbose_name='Login')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('tokens', models.BooleanField(blank=True, null=True, verbose_name='Tokens')),
                ('campaigns', models.IntegerField(blank=True, null=True, verbose_name='Campaigns')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_manager.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('traffic_group', models.CharField(choices=[('ADMIN', 'ADMIN'), ('FPA/HSA/PWA', 'FPA/HSA/PWA'), ('INAPP traff', 'INAPP traff'), ('NATIVE traff', 'NATIVE traff'), ('POP traff', 'POP traff'), ('PUSH traff', 'PUSH traff')], max_length=16, verbose_name='Traffic group')),
                ('offers_list', models.ManyToManyField(related_name='campaigns_list', to='bot_manager.Offer', verbose_name='Offers')),
                ('traffic_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.trafficsource', verbose_name='Traffic source')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_manager.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], verbose_name='Type')),
                ('condition', models.TextField(max_length=16384, verbose_name='Condition')),
                ('action', models.CharField(choices=[('Stop campaign', 'Stop campaign'), ('Start campaign', 'Start campaign'), ('Add landing to BL', 'Add landing to BL'), ('Add landing to WL', 'Add landing to WL')], max_length=128, verbose_name='Action')),
                ('checking_interval', models.TimeField(verbose_name='Condition checking interval')),
                ('list_type', models.PositiveSmallIntegerField(null=True, verbose_name='List type')),
                ('landing_exceptions', models.TextField(blank=True, null=True, verbose_name='Landing exceptions')),
                ('campaigns_list', models.ManyToManyField(to='bot_manager.Campaign', verbose_name='Campaigns list')),
            ],
        ),
    ]
