# Generated by Django 3.1.1 on 2020-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Status'),
        ),
    ]
