# Generated by Django 3.1.1 on 2020-09-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0002_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_manager.user', verbose_name='User'),
            preserve_default=False,
        ),
    ]
