# Generated by Django 3.1.1 on 2020-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0003_bot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='landing_exceptions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Landing exceptions'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='list_type',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='List type'),
        ),
    ]
