# Generated by Django 3.1.1 on 2020-09-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0004_auto_20200927_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='checking_interval',
        ),
    ]
