# Generated by Django 3.1.1 on 2020-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0005_remove_bot_checking_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='checking_interval',
            field=models.PositiveIntegerField(default=0, verbose_name='Condition checking interval'),
            preserve_default=False,
        ),
    ]
