# Generated by Django 3.1.1 on 2020-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0008_auto_20200927_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.CharField(choices=[('stop_campaign', 'Stop campaign'), ('start_campaign', 'Start campaign'), ('add_to_bl', 'Add landing to BL'), ('add_to_wl', 'Add landing to WL')], max_length=128, verbose_name='Action'),
        ),
    ]
