# Generated by Django 3.1.1 on 2020-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0009_auto_20200927_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], default='disabled', max_length=8, verbose_name='Status (enabled/disabled)'),
        ),
    ]
