# Generated by Django 3.1.1 on 2020-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0010_bot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='landing_exceptions',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='list_type',
        ),
        migrations.AddField(
            model_name='bot',
            name='ignored_sources',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Ignored sources'),
        ),
    ]
