# Generated by Django 3.1.1 on 2020-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0011_auto_20201001_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='filtering_param_name',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Param name for filtering campaign's statistics by sources."),
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='filtering_param_number',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Number of param for filtering campaign's statistics by sources."),
        ),
    ]
