# Generated by Django 3.1.1 on 2020-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0012_auto_20201002_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsource',
            name='filtering_param_number',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name="Number of param for filtering campaign's statistics by sources."),
        ),
    ]
