# Generated by Django 3.1.1 on 2020-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0013_auto_20201002_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_checked',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last checked'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ignored_sources',
            field=models.TextField(default=None, null=True, verbose_name='Ignored sources'),
        ),
    ]
