# Generated by Django 3.1.1 on 2020-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0014_auto_20201003_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='checking_interval',
        ),
        migrations.AddField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='-', max_length=65536, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'Stop campaign'), (1, 'Start campaign'), (2, 'Add landing to BL'), (3, 'Add landing to WL')], verbose_name='Action'),
        ),
    ]
