# Generated by Django 3.1.1 on 2020-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0015_auto_20201005_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.SmallIntegerField(choices=[(3, 'Stop campaign'), (4, 'Start campaign'), (2, 'Add landing to BL'), (1, 'Add landing to WL')], verbose_name='Action'),
        ),
    ]
