# Generated by Django 3.1.1 on 2020-10-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0016_auto_20201005_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='last_checked',
        ),
    ]
