# Generated by Django 3.1.1 on 2020-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0017_remove_bot_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='Period for statistics checking'),
            preserve_default=False,
        ),
    ]
