# Generated by Django 3.1.1 on 2020-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0018_bot_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], default='enabled', max_length=8, verbose_name='Status (enabled/disabled)'),
        ),
    ]
