# Generated by Django 3.1.1 on 2020-10-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0020_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='campaign_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_manager.campaign', verbose_name='Campaign ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='site_id',
            field=models.CharField(default=None, max_length=512, verbose_name='Site ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.SmallIntegerField(default=None, verbose_name='Status (added to wl/bl)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=512, null=True, verbose_name='Name'),
        ),
    ]
