# Generated by Django 3.1.1 on 2020-10-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0021_auto_20201009_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='campaign_id',
            new_name='campaign',
        ),
    ]
