# Generated by Django 3.1.1 on 2020-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0022_auto_20201009_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=2048, verbose_name='Site ID'),
        ),
    ]
