# Generated by Django 3.1.1 on 2020-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0023_auto_20201009_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.SmallIntegerField(default=-1, null=True, verbose_name='Status'),
        ),
    ]
