# Generated by Django 3.1.1 on 2020-10-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0024_auto_20201009_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='offers_list',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='traffic_group',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
    ]
