# Generated by Django 3.1.1 on 2020-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0026_auto_20201010_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.IntegerField(verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
