# Generated by Django 3.1.1 on 2020-10-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0027_auto_20201010_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsource',
            name='campaigns',
        ),
    ]
