# Generated by Django 3.1.1 on 2020-10-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0028_remove_trafficsource_campaigns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
