# Generated by Django 3.1.1 on 2020-10-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0029_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficsource',
            old_name='filtering_param_name',
            new_name='filtering_param_name_sources',
        ),
        migrations.RenameField(
            model_name='trafficsource',
            old_name='filtering_param_number',
            new_name='filtering_param_number_sources',
        ),
    ]
