# Generated by Django 3.1.1 on 2020-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0030_auto_20201012_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsource',
            name='filtering_param_name_campaigns',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Param name for filtering campaign's statistics by campaigns."),
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='filtering_param_number_campaigns',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name="Number of param for filtering campaign's statistics by campaigns."),
        ),
    ]
