# Generated by Django 3.1.1 on 2020-10-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0031_auto_20201012_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
    ]
