# Generated by Django 3.1.1 on 2020-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0032_remove_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='source_info',
            field=models.TextField(default=None, max_length=65536, null=True, verbose_name='Source info'),
        ),
    ]
