# Generated by Django 3.1.1 on 2021-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0033_bot_source_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='traffic_source',
            field=models.CharField(choices=[('Propeller Ads', 'Propeller Ads')], max_length=256, verbose_name='Traffic source'),
        ),
    ]
