# Generated by Django 3.1.1 on 2021-01-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0034_auto_20210106_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficSource',
        ),
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.SmallIntegerField(choices=[(2, 'Stop campaign'), (1, 'Start campaign')], verbose_name='Action'),
        ),
    ]
