# Generated by Django 3.1.1 on 2021-01-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0035_auto_20210106_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='traffic_source',
            field=models.CharField(choices=[('Propeller Ads', 'Propeller Ads')], default=1, max_length=256, verbose_name='Traffic source'),
            preserve_default=False,
        ),
    ]
