# Generated by Django 3.1.5 on 2021-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0036_bot_traffic_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='ts_api_key',
            field=models.CharField(default='a', max_length=1024, verbose_name='TS api key'),
            preserve_default=False,
        ),
    ]
