# Generated by Django 3.1.5 on 2021-01-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0037_bot_ts_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='source_info',
        ),
    ]
