# Generated by Django 3.1.5 on 2021-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0038_remove_bot_source_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
