# Generated by Django 3.1.5 on 2021-01-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0039_delete_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon:\ntue:\nwed:\nthu:\nfri:\nsat:\nsun:\n', max_length=65536, verbose_name='Schedule'),
        ),
    ]
