# Generated by Django 3.1.5 on 2021-01-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0041_auto_20210113_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon: \ntue: \nwed: \nthu: \nfri: \nsat: \nsun: \n', help_text='Example:\nmon: 10:00-12:30[5], 14:00\ntue: 12:00, 13:30, 15:00-18:00[10]\nwed: 11:00, 19:00\nthu: 01:00-23:00[15]\nfri: 10:00, 14:00-15:00[7]\nsat: \nsun: 8:00\n', max_length=65536, verbose_name='Schedule'),
        ),
    ]
