# Generated by Django 3.1.5 on 2021-01-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0043_auto_20210113_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon: \ntue: \nwed: \nthu: \nfri: \nsat: \nsun: \n', help_text='Example: mon: 10:00-12:30[5], 13:30, 15:00-18:00[10]', max_length=65536, verbose_name='Schedule'),
        ),
    ]
