# Generated by Django 3.1.5 on 2021-01-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0044_auto_20210113_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 1)], help_text='Type 1: bot for campaigns play/stop depending on condition', verbose_name='Type'),
        ),
    ]
