# Generated by Django 3.1.5 on 2021-01-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0045_auto_20210113_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='campaigns_list',
            field=models.ManyToManyField(help_text='If campaign doesn\'t exist, you can create it using "+"', to='bot_manager.Campaign', verbose_name='Campaigns list'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='condition',
            field=models.TextField(help_text='Example: ((CR < 1)&(clicks >= 50))', max_length=16384, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='period',
            field=models.PositiveIntegerField(help_text='Please specify the value in seconds', verbose_name='Period for statistics checking'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Play/stop campaign')], verbose_name='Type'),
        ),
    ]
