# Generated by Django 3.1.5 on 2021-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0046_auto_20210113_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.SmallIntegerField(choices=[(2, 'Stop campaign'), (1, 'Start campaign')], verbose_name='Target action'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='condition',
            field=models.TextField(help_text='Example: ((CR < 1) & (clicks >= 50))', max_length=16384, verbose_name='Condition'),
        ),
    ]
