# Generated by Django 3.1.5 on 2021-01-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0049_auto_20210113_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='crontab_salt',
            field=models.CharField(default='abc', max_length=256, verbose_name='Crontab task comment'),
            preserve_default=False,
        ),
    ]
