# Generated by Django 3.1.5 on 2021-01-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0050_bot_crontab_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='crontab_salt',
            field=models.CharField(default='empty', max_length=256, verbose_name='Crontab task comment'),
        ),
    ]
