# Generated by Django 3.1.5 on 2021-01-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0052_auto_20210113_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='period',
            field=models.SmallIntegerField(choices=[(1, 'Today'), (2, 'Yesterday'), (11, 'This week'), (13, 'Last 2 Days'), (14, 'Last 3 Days'), (3, 'Last 7 Days'), (4, 'Last 14 Days'), (5, 'This month'), (6, 'Last month'), (7, 'This year'), (9, 'All time')], verbose_name='Period for statistics checking'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon: \ntue: \nwed: \nthu: \nfri: \nsat: \nsun: \n', help_text="Example: mon: 10:00-12:30[5], 13:30, 15:00-18:00[10]. Note that checking interval can't be greater than 1440 minutes (24 hours). Please note that all time is UTC time.", max_length=65536, verbose_name='Schedule'),
        ),
    ]
