# Generated by Django 3.1.5 on 2021-01-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0053_auto_20210115_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='id',
            new_name='source_id',
        ),
    ]
