# Generated by Django 3.1.5 on 2021-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0054_auto_20210115_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tracker_id',
            field=models.IntegerField(default=2, unique=True, verbose_name='Tracker ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='source_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Source ID'),
        ),
    ]
