# Generated by Django 3.1.5 on 2021-01-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0055_auto_20210115_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tracker_id',
            field=models.IntegerField(verbose_name='Tracker ID'),
        ),
    ]
