# Generated by Django 3.1.5 on 2021-01-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0056_auto_20210115_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='source_id',
            new_name='id',
        ),
    ]
