# Generated by Django 3.1.5 on 2021-01-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0059_auto_20210115_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='source_id',
            field=models.IntegerField(default=1, verbose_name='Source ID'),
            preserve_default=False,
        ),
    ]
