# Generated by Django 3.1.5 on 2021-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0060_campaign_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='source_id',
            field=models.CharField(max_length=64, verbose_name='Source ID'),
        ),
    ]
