# Generated by Django 3.1.5 on 2021-01-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0061_auto_20210115_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Traffic source')),
                ('filter_param_number', models.SmallIntegerField(verbose_name='Param number in tracker')),
            ],
        ),
    ]
