# Generated by Django 3.1.5 on 2021-01-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0062_trafficsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='traffic_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_manager.trafficsource', verbose_name='Traffic source'),
        ),
    ]
