# Generated by Django 3.1.5 on 2021-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0063_auto_20210126_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsource',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Traffic source'),
        ),
    ]
