# Generated by Django 3.1.5 on 2021-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0065_auto_20210127_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Play/stop campaign'), (2, 'Add to black/white list')], verbose_name='Type'),
        ),
    ]
