# Generated by Django 3.1.5 on 2021-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0066_auto_20210127_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='campaigns_list',
            field=models.ManyToManyField(help_text='If campaign doesn\'t exist, you can create it here using "+"', to='bot_manager.Campaign', verbose_name='Campaigns list'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ignored_sources',
            field=models.TextField(default=None, help_text='Please specify each ignored source on a new line', null=True, verbose_name='Ignored sources'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(help_text='Any string up to 128 characters', max_length=128, verbose_name='Name'),
        ),
    ]
