# Generated by Django 3.1.5 on 2021-01-29 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_manager', '0067_auto_20210127_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='ignored_sources',
        ),
        migrations.AddField(
            model_name='bot',
            name='ignored_zones',
            field=models.TextField(default=None, help_text='Please specify each zone on a new line', null=True, verbose_name='Ignored zones'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='campaigns_list',
            field=models.ManyToManyField(help_text='If campaign doesn\'t exist, you can create it here using "+".\n', to='bot_manager.Campaign', verbose_name='Campaigns'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(help_text='Only superuser can change this field', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
