# Generated by Django 3.1.5 on 2021-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0068_auto_20210129_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='campaigns_list',
            field=models.ManyToManyField(help_text='If campaign doesn\'t exist, you can create it here using "+".', to='bot_manager.Campaign', verbose_name='Campaigns'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon: \ntue: \nwed: \nthu: \nfri: \nsat: \nsun: \n', help_text="Example: mon: 10:00-12:30[5], 13:30, 15:00-18:00[10]. Note that checking interval can't be greater than 1440 minutes (24 hours). All time is UTC time.", max_length=65536, verbose_name='Schedule'),
        ),
    ]
