# Generated by Django 3.1.5 on 2021-01-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0069_auto_20210129_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ignored_zones',
            field=models.TextField(blank=True, default=None, help_text='Please specify each zone on a new line', null=True, verbose_name='Ignored zones'),
        ),
    ]
