# Generated by Django 3.1.5 on 2021-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0071_auto_20210129_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tracker_id',
            field=models.PositiveSmallIntegerField(verbose_name='Tracker ID'),
        ),
    ]
