# Generated by Django 3.1.5 on 2021-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0072_auto_20210129_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, help_text='Any string up to 256 symbols', max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='source_id',
            field=models.CharField(help_text='Campaign ID from traffic source (up to 128 symbols)', max_length=128, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tracker_id',
            field=models.PositiveSmallIntegerField(help_text='Campaign ID from tracker', verbose_name='Tracker ID'),
        ),
    ]
