# Generated by Django 3.1.5 on 2021-01-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0073_auto_20210129_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.SmallIntegerField(choices=[(2, 'Stop campaign'), (1, 'Play campaign'), (3, 'Exclude zone'), (4, 'Include zone')], verbose_name='Target action'),
        ),
    ]
