# Generated by Django 3.1.5 on 2021-03-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0074_auto_20210129_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='list_to_add',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='List (audience for evadav)'),
        ),
    ]
