# Generated by Django 3.1.5 on 2021-03-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0075_bot_list_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='list_to_add',
            field=models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='List (audience for evadav)'),
        ),
    ]
