# Generated by Django 3.1.5 on 2021-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0076_auto_20210308_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='client_id',
            field=models.CharField(blank=True, default='-', max_length=128, null=True, verbose_name='Client key (for mgid)'),
        ),
    ]
