# Generated by Django 3.1.5 on 2021-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot_manager', '0077_bot_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.IntegerField(default=1, help_text='Only superuser can change this field', verbose_name='User'),
            preserve_default=False,
        ),
    ]
