# Generated by Django 3.1.5 on 2021-04-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0079_auto_20210329_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tracker',
            field=models.CharField(default='-', max_length=64, verbose_name='Tracker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='tracker_api_key',
            field=models.CharField(default='-', max_length=128, verbose_name='Tracker API key'),
            preserve_default=False,
        ),
    ]
