# Generated by Django 3.1.5 on 2021-04-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0080_auto_20210404_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
