# Generated by Django 3.1.5 on 2021-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0081_delete_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tracker_url',
            field=models.CharField(default='-', max_length=256, verbose_name='Tracker url for requests'),
            preserve_default=False,
        ),
    ]
