# Generated by Django 3.1.5 on 2021-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0082_bot_tracker_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='list_to_add',
            field=models.CharField(blank=True, default='-', max_length=128, null=True, verbose_name='List (audience for evadav)'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='schedule',
            field=models.TextField(default='mon: \ntue: \nwed: \nthu: \nfri: \nsat: \nsun: \n', help_text="Example: mon: 10:00-12:30[5], 13:30, 15:00-18:00[10]. Note that checking interval can't be greater than 1440 minutes (24 hours). All time is UTC time.", max_length=16384, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ts_api_key',
            field=models.CharField(max_length=128, verbose_name='TS api key'),
        ),
    ]
