# Generated by Django 3.1.5 on 2021-04-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0083_auto_20210413_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsource',
            name='filter_param_number',
        ),
        migrations.AddField(
            model_name='trafficsource',
            name='binom_param_number',
            field=models.SmallIntegerField(default=1, verbose_name='Param number in Binom'),
            preserve_default=False,
        ),
    ]
