# Generated by Django 3.1.5 on 2021-04-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0084_auto_20210414_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='user',
            new_name='user_id',
        ),
    ]
