# Generated by Django 3.1.5 on 2021-04-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0085_auto_20210416_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='tracker_url',
            new_name='tracker_requests_url',
        ),
    ]
