# Generated by Django 3.1.5 on 2021-04-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0086_auto_20210416_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='campaigns_list',
            new_name='campaigns_ids',
        ),
    ]
