# Generated by Django 3.1.5 on 2021-04-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0087_auto_20210416_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='list_to_add',
            new_name='list_id',
        ),
    ]
