# Generated by Django 3.1.5 on 2021-04-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_manager', '0088_auto_20210416_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='ignored_zones',
            new_name='ignored_sources',
        ),
    ]
